apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: monster-frontend
spec:
  type: NodePort
  selector:
    app: monster-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
