/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/monsters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MonsterController_getAllMonsters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/monsters/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MonsterController_getMonsterById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/monsters/type/{type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MonsterController_getMonstersByType"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        MonsterDto: {
            /** @example 1 */
            id: number;
            /** @example Monster Energy */
            name: string;
            /**
             * @description The Monster product type (e.g., Ultra, Punch, Energy).
             * @example Ultra
             * @enum {string}
             */
            type: "Energy" | "Ultra" | "Java" | "Punch" | "Rehab" | "MAXX" | "X-Presso" | "Dragon Tea" | "Espresso" | "Muscle" | "Hydro";
            /** @example The monster ultra white is a refreshing energy drink with a crisp taste. */
            description: string;
            /** @example 2.99 */
            price: number;
            /** @example https://example.com/monster-ultra-white.jpg */
            imageUrl: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    MonsterController_getAllMonsters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonsterDto"][];
                };
            };
        };
    };
    MonsterController_getMonsterById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonsterDto"];
                };
            };
        };
    };
    MonsterController_getMonstersByType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The Monster product type (e.g., Ultra, Punch, Energy). */
                type: "Energy" | "Ultra" | "Java" | "Punch" | "Rehab" | "MAXX" | "X-Presso" | "Dragon Tea" | "Espresso" | "Muscle" | "Hydro";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonsterDto"][];
                };
            };
        };
    };
}
